package com.mysite.sbb.mySong;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class Find_Your_One_Way {
	@GetMapping("/Find Your One Way")
	@ResponseBody
	public String index() {
		return("need it back!<br>"
				+ "되찾아!<br>"
				+ "yes, nobody is gone<br>"
				+ "그래, 아무도 안 죽었어<br>"
				+ "i'm just saying that<br>"
				+ "그냥 내 말 듣고<br>"
				+ "step it, buddy!<br>"
				+ "춤춰봐, 친구!<br>"
				+ "do it out of turn!<br>"
				+ "규칙은 신경 쓰지 마!<br>"
				+ "don't freak out!<br>"
				+ "겁낼 것 없어!<br>"
				+ "yes, nobody is wrong<br>"
				+ "누구의 잘못도 아냐<br>"
				+ "you and i both just have our views<br>"
				+ "너랑 나도 관점이 다를 뿐<br>"
				+ "that's all<br>"
				+ "그것뿐이지<br>"
				+ "<br>"
				+ "somebody will make me do crazy shit<br>"
				+ "누군가 나에게 미친 짓을 시키려 해<br>"
				+ "when have i ever forced you to do that?<br>"
				+ "내가 언제 너에게 강요했지?<br>"
				+ "give me my place back<br>"
				+ "내 자리를 돌려줘<br>"
				+ "and i won't take your special place, Deal?(No!)<br>"
				+ "그러면 나도 네 자리를 뺏지 않겠어, 어때?(아니!)<br>"
				+ "the world is not so tight, right?<br>"
				+ "이 세상도 그렇게 빡빡하진 않지?<br>"
				+ "<br>"
				+ "strike back! (go excited)<br>"
				+ "맞서 싸워! (신나게!)<br>"
				+ "get them out of your way<br>"
				+ "방해자는 모두 날려버려<br>"
				+ "you don't care if along the way is a little sacrifice<br>"
				+ "작은 희생 따윈 아무것도 아니지<br>"
				+ "strike back! (go excited)<br>"
				+ "맞서 싸워! (신나게!)<br>"
				+ "get them out of your way (Yeah)<br>"
				+ "방해자는 모두 날려버려<br>"
				+ "don't melt in the world<br>"
				+ "세계 속으로 녹아들지 마<br>"
				+ "find your one way<br>"
				+ "너만의 길을 찾아<br>"
				+ "<br>"
				+ "give that back!<br>"
				+ "돌려줘!<br>"
				+ "nobody will miss it!<br>"
				+ "아무도 관심 없을 거야!<br>"
				+ "i'm just saying that<br>"
				+ "그냥 내 말 듣고<br>"
				+ "step it, buddy!<br>"
				+ "춤춰봐, 친구!<br>"
				+ "do it out of turn<br>"
				+ "규칙은 신경 쓰지 마!<br>"
				+ "sit back down!<br>"
				+ "이제 앉아봐!<br>"
				+ "'cause nobody denies it<br>"
				+ "아무도 부정하지 않을 테니까<br>"
				+ "you and i both just have our views<br>"
				+ "너도 나도 관점이 다를 뿐<br>"
				+ "that's all<br>"
				+ "그것뿐이지<br>"
				+ "<br>"
				+ "you're not me<br>"
				+ "너는 내가 아냐<br>"
				+ "you're not the law<br>"
				+ "너는 규칙이 아냐<br>"
				+ "you are not my downfall, either<br>"
				+ "너는 나의 파멸도 아니지<br>"
				+ "if your voices will fill the sky<br>"
				+ "네 목소리가 하늘을 채운다면<br>"
				+ "i'll take the wasteland<br>"
				+ "나는 황야를 갖겠어<br>"
				+ "but i won't be alone<br>"
				+ "하지만 고독하진 않겠지<br>"
				+ "never!<br>"
				+ "절대로!<br>"
				+ "<br>"
				+ "strike back! (go excited)<br>"
				+ "맞서 싸워! (신나게!)<br>"
				+ "get them out of your way<br>"
				+ "방해자는 모두 날려버려<br>"
				+ "you don't care if along the way is a little sacrifice<br>"
				+ "작은 희생 따윈 아무것도 아니지<br>"
				+ "strike back! (go excited)<br>"
				+ "맞서 싸워! (신나게!)<br>"
				+ "get them out of your way (Yeah)<br>"
				+ "방해자는 모두 날려버려<br>"
				+ "don't melt in the world<br>"
				+ "세계 속으로 녹아들지 마<br>"
				+ "find your one way<br>"
				+ "너만의 길을 찾아<br>"
				+ "<br>"
				+ "let's go and step it, buddy!<br>"
				+ "함께 춤을 추자고, 친구!<br>"
				+ "<br>"
				+ "step it, buddy, step it, buddy!<br>"
				+ "춤춰 봐 친구, 춤 춰 보자구!<br>"
				+ "<br>"
				+ "strike back! (go excited)<br>"
				+ "맞서 싸워! (신나게!)<br>"
				+ "get them out of your way<br>"
				+ "방해자는 모두 날려버려<br>"
				+ "you don't care if along the way is a little sacrifice<br>"
				+ "작은 희생 따윈 아무것도 아니지<br>"
				+ "strike back! (go excited)<br>"
				+ "맞서 싸워! (신나게!)<br>"
				+ "get them out of your way (Yeah)<br>"
				+ "방해자는 모두 날려버려<br>"
				+ "listen to your heart<br>"
				+ "네 가슴의 소리를 들어<br>"
				+ "not the voice in your head!<br>"
				+ "네 머릿속 헛소리는 무시해!<br>"
				+ "<br>"
				+ "strike back! (go excited)<br>"
				+ "맞서 싸워! (신나게!)<br>"
				+ "get them out of your way<br>"
				+ "방해자는 모두 날려버려<br>"
				+ "you don't care if along the way is a little sacrifice<br>"
				+ "작은 희생 따윈 아무것도 아니지<br>"
				+ "strike back! (go excited)<br>"
				+ "맞서 싸워! (신나게!)<br>"
				+ "get them out of your way (Yeah)<br>"
				+ "방해자는 모두 날려버려<br>"
				+ "don't melt in the world<br>"
				+ "세계 속으로 녹아들지 마<br>"
				+ "find your one way<br>"
				+ "너만의 길을 찾아");
	}
}
