package com.mysite.sbb;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class The_Roar_of_the_Spark {
	@GetMapping("/The Roar of the Spark")
	@ResponseBody
	public String index() {
		return("Through the darkest sky<br>"
				+ "어두운 하늘 속으로<br>"
				+ "Groping for the light<br>"
				+ "빛을 향해 손을 뻗는다<br>"
				+ "Like crying for the moon<br>"
				+ "달을 향해 울부짖듯<br>"
				+ "<br>"
				+ "Never-ending black<br>"
				+ "끝이 없는 암흑<br>"
				+ "Forgot what I want<br>"
				+ "원하는 것도 잊었지만<br>"
				+ "Never felt that hard to me<br>"
				+ "한 번도 힘든 적은 없었지<br>"
				+ "<br>"
				+ "That's right, go forth<br>"
				+ "Don't look back<br>"
				+ "그래 나아가라, 돌아보지 말고<br>"
				+ "I can believe in the path I'm on<br>"
				+ "내가 가는 길을 믿으며<br>"
				+ "Faith, pride<br>"
				+ "신뢰, 긍지<br>"
				+ "So what do I have to fear?<br>"
				+ "무엇이 두렵단 말인가?<br>"
				+ "<br>"
				+ "Under the sacred briars<br>"
				+ "성스러운 가시덤불 아래서<br>"
				+ "Never stop, just go<br>"
				+ "멈추지 말고 가라<br>"
				+ "I don't care how many more scars I get<br>"
				+ "상처 입는 것은 신경 쓰지 않아<br>"
				+ "Bearing a pale fire<br>"
				+ "희미한 불꽃을 두르고<br>"
				+ "I'm going as far as I can<br>"
				+ "누구보다도 빨리 달려가겠어<br>"
				+ "I hope my path will be<br>"
				+ "내가 가는 길은<br>"
				+ "A guide of light for someone to follow<br>"
				+ "뒤따르는 자를 인도하는 빛<br>"
				+ "The roar of the spark<br>"
				+ "섬광의 포효가 되리<br>"
				+ "<br>"
				+ "The dawn that burns my eyes<br>"
				+ "내 눈을 태우는 여명<br>"
				+ "What a strange scent<br>"
				+ "기묘한 향기가 흐르고<br>"
				+ "Sound that comes flooding in<br>"
				+ "봇물처럼 터져나오는 소리들<br>"
				+ "<br>"
				+ "Never-ending white<br>"
				+ "끝이 없는 백색<br>"
				+ "Forgot what I want<br>"
				+ "원하는 것도 잊었어<br>"
				+ "Is this Arcadia?<br>"
				+ "여기가 이상향인가?<br>"
				+ "<br>"
				+ "I don't know what's right for the world<br>"
				+ "무엇이 옳은 것인지 나는 알 수 없어<br>"
				+ "Oh, I may have lost my way<br>"
				+ "길을 잃은 것인지도 모르지<br>"
				+ "But there's no reason to doubt it now<br>"
				+ "하지만 이제는 의심할 이유도 없어<br>"
				+ "So what do I have to fear?<br>"
				+ "무엇이 두렵단 말인가?<br>"
				+ "<br>"
				+ "Under the sacred briars<br>"
				+ "성스러운 가시덤불 아래서<br>"
				+ "Never stop, just go<br>"
				+ "멈추지 말고 가라<br>"
				+ "I don't care how many more scars I get<br>"
				+ "상처 입는 것은 신경 쓰지 않아<br>"
				+ "Bearing a pale fire<br>"
				+ "희미한 불꽃을 두르고<br>"
				+ "I'm going as far as I can<br>"
				+ "누구보다도 빨리 달려가겠어<br>"
				+ "I hope my path will be<br>"
				+ "내가 가는 길은<br>"
				+ "A guide of light for someone to follow<br>"
				+ "뒤따르는 자를 인도하는 빛<br>"
				+ "The roar of the spark<br>"
				+ "섬광의 포효가 되리<br>"
				+ "<br>"
				+ "Dive the deep blue sea<br>"
				+ "깊고 푸른 바다로 뛰어들어<br>"
				+ "It is hard to breathe<br>"
				+ "숨쉬기가 힘들어지고<br>"
				+ "The light goes out again<br>"
				+ "빛은 다시 사라져가네<br>"
				+ "<br>"
				+ "Never-ending road<br>"
				+ "끝이 없는 길<br>"
				+ "A place without color<br>"
				+ "색이 없는 공간<br>"
				+ "That's the world we can dye<br>"
				+ "우리가 물들일 수 있는 세계<br>"
				+ "<br>"
				+ "That's right, go forth<br>"
				+ "Don't look back<br>"
				+ "그래 나아가라, 돌아보지 말고<br>"
				+ "I can believe in the path I'm on<br>"
				+ "내가 가는 길을 믿으며<br>"
				+ "Faith, pride<br>"
				+ "신뢰, 긍지<br>"
				+ "So what do I have to fear?<br>"
				+ "무엇이 두렵단 말인가?<br>"
				+ "<br>"
				+ "Under the lonely moon<br>"
				+ "고독한 달 아래<br>"
				+ "In an influx of words<br>"
				+ "쏟아져 들어오는 말들 속에서<br>"
				+ "This road shines with my colors<br>"
				+ "나의 색으로 빛나는 이 길<br>"
				+ "Bearing a pale fire<br>"
				+ "희미한 불꽃을 두르고<br>"
				+ "I'm going as far as I can<br>"
				+ "누구보다도 빨리 달려가겠어<br>"
				+ "To keep the glow alive<br>"
				+ "이 빛을 영원히 지키기 위해<br>"
				+ "<br>"
				+ "Under the sacred briars<br>"
				+ "성스러운 가시덤불 아래서<br>"
				+ "Never stop, just go<br>"
				+ "멈추지 말고 가라<br>"
				+ "I don't care how many more scars I get<br>"
				+ "상처 입는 것은 신경 쓰지 않아<br>"
				+ "Bearing a pale fire<br>"
				+ "희미한 불꽃을 두르고<br>"
				+ "I'm going as far as I can<br>"
				+ "누구보다도 빨리 달려가겠어<br>"
				+ "It will be endless<br>"
				+ "끝도 없으며<br>"
				+ "And it's not an easy journey<br>"
				+ "결코 쉽지 않은 길<br>"
				+ "Hoping to fill the world<br>"
				+ "눈부신 빛들이<br>"
				+ "with all kinds of light<br>"
				+ "세상을 비추게 되길 바라며");
	}
}
